version: '3.7'
services:
    app:
        build:
            args:
                user: ${USER}
                uid: 1000
            context: ./
            dockerfile: ./docker/php/Dockerfile
        image: urlshort
        container_name: urlshort-app
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
            - ./:/var/www
        networks:
            - urlshort
    db:
        image: mysql:5.7
        container_name: urlshort-db
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: urlshort
            MYSQL_ROOT_PASSWORD: root
            MYSQL_PASSWORD: root
            SERVICE_TAGS: dev
            SERVICE_NAME: mysql
        volumes:
            - ./docker/mysql:/docker-entrypoint-initdb.d
        networks:
            - urlshort
    nginx:
        image: nginx:alpine
        container_name: urlshort-nginx
        restart: unless-stopped
        ports:
            - 8000:80
        volumes:
            - ./:/var/www/
            - ./docker/nginx:/etc/nginx/conf.d/
        networks:
            - urlshort
networks:
    urlshort:
        driver: bridge
